theme: jekyll-theme-minimal
title: Jake Wallace
# description: I am a developer specializing in TypeScript and the JavaScript ecosystem. I enjoy making games.
description:
  <p align="center">
    <a href="https://www.youtube.com/">     
      <img
        alt="Jake Wallace's YouTube Profile"
        src="./assets/icons/youtube2.png"
        width="50"
        style="padding-left:5px;"
      />
    </a>
    <a href="https://www.instagram.com/jakewallace.io/">     
      <img
        alt="Jake Wallace's Instagram Profile"
        src="./assets/icons/instagram.png"
        width="50"
        style="padding-left:5px;"
      />
    </a>
    <a href="https://www.linkedin.com/in/jacob-wallace">     
      <img
        alt="Jake Wallace's LinkedIn Profile"
        src="./assets/icons/linkedin2.png"
        width="50"
        style="padding-left:5px;"
      />
    </a>
    <a href="https://github.com/jjwall">     
      <img
        alt="Jake Wallace's GitHub Profile"
        src="./assets/icons/github2.png"
        width="55"
        style="padding-left:5px;top:5px;"
      />
    </a>
  </p>
logo: /assets/images/Jake_2023_cropped.png
github: false