theme: jekyll-theme-minimal
title: Jake Wallace
# description: I am a developer specializing in TypeScript and the JavaScript ecosystem. I enjoy making games.
description:     
  <img
    alt="Exquisite Adventure"
    src="./assets/images/exq_adv_dark.png"
    width="50"
  />
logo: /assets/images/Jake_2023_cropped.png